### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by jeesnl**

### CODE REVIEW

**Comment by knolleary** [comment]
Please can you explain the nature of the change?

We set Node-RED version to 1.x so it will always pickup the latest stable release. You have changed that to hard code to an old version. 1.2.9 is the latest.

**Comment by jeesnl** [comment]
Hello,

i was not aware that i changed this in the master. how can i undo this?

kind regards, Jan

**Comment by knolleary** [comment]
If this isn't something you want us to merge, you can just close the pull request

**Comment by jeesnl** [comment]
Sorry for the mistake.

**Pull request closed without merging**
